### ISSUE TITLE
Inline CommonJS requires for bh-bundle tech

### ISSUE THREAD

**Issue by blond** [enb-bem/enb-bh#103]
```js
requires: {
    lib: {
        commonJS: 'path/to/module'
    }
}
```

Now the code will contain a line with `require('path/to/module')`. Such file can not be used in a browser.

**Comment by gela-d** [comment]
Наработки тут https://github.com/enb-bem/enb-bh/commit/be40ec60105eb397a61b10844b4a977ae7e06573
