### ISSUE TITLE
bhOptions

### ISSUE THREAD

**Issue by blond** [enb-bem/enb-bh#119]
Use `bhOptions` instead of all options for provide to core:

* `jsAttrName`
* `jsAttrScheme`
* `jsCls`
* `jsElem`
* `escapeContent`
* `clsNobaseMods`

This change will allow:

1. We do not need to release new versions of `enb-bh` if released minor versions of `bh` with new option.
2. Test `bh` package before its release (see #118)

**Comment by sipayRT** [comment]
:+1:

**Comment by zxqfox** [comment]
Would you mind to declare peer dep for bh?

**Comment by blond** [comment]
> Would you mind to declare peer dep for bh?

What for?

**Comment by zxqfox** [comment]
Just to declare what version of bh it supports. NPM won't install it if it declared since https://github.com/npm/npm/issues/6565#issuecomment-74971689 — so it will be pretty usable in 3.0

**Comment by blond** [comment]
I think that it will be useful when most users will use `npm@3.0`. Now it will bring more problems than profit.

**Comment by zxqfox** [comment]
Ye, forgot about node 0.12 users. ;-( sorree
