### ISSUE TITLE
Add support for jsElem param of bh

### ISSUE THREAD

**Issue by narqo** [enb-bem/enb-bh#26]
See bem/bh#119

**Comment by aristov** [comment]
@blond ping

**Comment by blond** [comment]
`bh` does not have `jsElem` option. If mode is set with a value of `true`, then `i-bem` class will be added for block and for elem. There is no way to control it.

In the issue https://github.com/bem/bh/issues/119, added the option `jsCls` option. It allows you to customize the name of the `i-bem` class.

**Comment by blond** [comment]
@mishanga Maybe we need to implement `jsElem` option in `bh`?

**Comment by mishanga** [comment]
Yep, I think we should.
