### ISSUE TITLE
Imitate BEMHTML export behaviour

### ISSUE THREAD

**Issue by tadatuta** [enb-bem/enb-bh#27]
Now we have `require('bundle.bh.js').apply()` but `requre('bundle.bemhtml.js').BEMHTML.apply()`.

I suggest to add `mimic` option as an array of names to additional export.

**Comment by arikon** [comment]
@tadatuta What do you mean?

**Comment by tadatuta** [comment]
@arikon added description

**Comment by arikon** [comment]
@tadatuta :+1:
