### ISSUE TITLE
Suport BH@v4.x

### ISSUE THREAD

**Issue by mishanga** [enb-bem/enb-bh#30]
https://github.com/bem/bh/releases/tag/v4.0.0

**Comment by dfilatov** [comment]
Is there any progress? It's really difficult to use the newest bh without this support.

**Comment by bratva** [comment]
+1 we need it

**Comment by tadatuta** [comment]
blocked by issue with tests: https://github.com/enb-bem/enb-bh/pull/32

**Comment by tsofist** [comment]
@blond Андрей, я так понимаю изменение пойдет в ближайший tag? А не подскажете когда его планируете выкатить?

**Comment by blond** [comment]
@tsofist, изменение войдёт в `v1.0.0`. 

Оставшиеся задачи — https://github.com/enb-bem/enb-bh/milestones/1.0

Задач не много, но это займёт какое-то время. Основное это документация и руководство по миграции.

Если очень нужно прямо сейчас, могу выпустить `enb-bh@1.0.0-alpha1`.

**Comment by tsofist** [comment]
@blond, спасибо. 
Вроде не горит, так что не к чему вас торопить - подождём.

**Comment by mishanga** [comment]
Мне горит :) Буду несказанно благодарен за альфу.

**Comment by tadatuta** [comment]
Может сначала сделать https://github.com/enb-bem/enb-bh/issues/26, чтобы альфу можно было и на коде islands потестить?

**Comment by blond** [comment]
@mishanga, выпустил `enb-bh@1.0.0-alpha1`.

@tadatuta выпустить вторую альфу после добавления #26 не проблема ;)

**Comment by mishanga** [comment]
@blond а ты её в npm не опубликовал еще?

**Comment by blond** [comment]
@mishanga опубликовал конечно. 

```console
$ npm i enb-bh@alpha
```

или точная версия

```console
$ npm i enb-bh@1.0.0-alpha1
```

**Comment by mishanga** [comment]
простите, туплю

**Comment by arikon** [comment]
@tadatuta Разве `jsElem` нужно в `islands`?

**Comment by blond** [comment]
@arikon по умолчанию `bh@4.0.0` добавляет `i-bem` класс к элементам. 

В `islands` нужно, чтобы `i-bem` добавлялся только к блокам. https://github.com/bem/bh/pull/148

**Comment by arikon** [comment]
@blond Понял, спасибо
